port: 7880

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: false

webhook:
  api_key: ACTUAL_LIVEKIT_API_KEY
  urls:
    - http://host.docker.internal:8080/api/v1/livekit/webhook
